# deploying to backend
push-to-dockerhub:
  image: docker:latest
  stage:
    - build
    - push
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  build_image:
    stage: build
    script:
      - echo "building the image"
      - docker build -t $DOCKER_IMAGE:$DOCKER_TAG ./backend
      - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
      - echo "build complete"
  push_image:
    stage: push
    script:
      - echo "pushing the image"
      - docker push $DOCKER_IMAGE:$DOCKER_TAG
      - docker push $DOCKER_IMAGE:latest
      - echo "Push Complete"
