name: push to dockerhub and deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: sahilpatilonelabventures/user-management:latest
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Pulling Docker image..."
            sudo docker pull sahilpatilonelabventures/user-management:latest
            echo "Stopping existing container..."
            sudo docker stop user-management || true
            echo "Removing existing container..."
            sudo docker rm user-management || true
            echo "Starting new container..."
            sudo docker run -d \
              --name user-management \
              -p 8080:8080 \
              -e MONGO_URL=${{ secrets.MONGO_URL }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              sahilpatilonelabventures/user-management:latest
